### ISSUE TITLE
Missing some file

### ISSUE THREAD

**Issue by ghost** [yu55/multi-am2301#1]
Can't find the file multi-am2301.c you mention under installation.

**Comment by yu55** [comment]
Thank you @louisluyckx1telenetbe  for your comment.
After 2 years you discovered that there is a bug in README - it should be decoder.c file (https://github.com/yu55/multi-am2301/blob/master/module/decoder.c), not multi-am2301.c.
I will fix this some time later.
Thanks.

**Comment by ghost** [comment]
Dear Marcin,

 

Thanks for your response.

I’m busy with testing a lot of temperature sensors to compare the stability and accuracy.

Till now I didn’t find a working script for the AM2301-DHT21. I now it’s an old version and replaced with the AM2302-DHT22. So I hope that this from you will work.

 

So my next problem is the following.

Installation

*	clone this repository
*	cd module
*	in source file multi-am2301.c find static int _pins[] = {23, 24, 25}; array initialization and correct GPIO logical pin numbers according to your needs (don't use board physical pin numbers!)
*	please check /lib/modules/VERSION/build directory in Makefile against your OS and correct if
*	needed. 

My version is 4.14.79+



              I have change “Makefile” like you describe.

 

MOD=multi-am2301

 

obj-m := $(MOD).o

 

$(MOD)-objs := decoder.o stats.o

 

all:

                              ARCH=arm CROSS_COMPILE=${CCPREFIX} $(MAKE) -C /lib/modules/4.14.79+/build M=$(PWD) modules

 

clean:

                              ARCH=arm CROSS_COMPILE=${CCPREFIX} $(MAKE) -C /lib/modules/4.14.79+/build M=$(PWD) clean

 

              But under this directory there is no “build “ directory.

This is what I have under  directory 4.14.79+

 

 



 

              The file modules.builtin contains the kernels

kernel/fs/binfmt_script.ko

kernel/fs/mbcache.ko

kernel/fs/autofs4/autofs4.ko

kernel/fs/cachefiles/cachefiles.ko

kernel/fs/configfs/configfs.ko

kernel/fs/exportfs/exportfs.ko

kernel/fs/ext4/ext4.ko

kernel/fs/f2fs/f2fs.ko

kernel/fs/fat/fat.ko

kernel/fs/fat/vfat.ko

kernel/fs/fat/msdos.ko

kernel/fs/fscache/fscache.ko

kernel/fs/jbd2/jbd2.ko

kernel/fs/lockd/lockd.ko

kernel/fs/nfs/nfs.ko

kernel/fs/nfs/nfsv2.ko

kernel/fs/nfs/nfsv3.ko

kernel/fs/nfs/nfsv4.ko

kernel/fs/nfs/filelayout/nfs_layout_nfsv41_files.ko

kernel/fs/nfs_common/nfs_acl.ko

kernel/fs/nfs_common/grace.ko

kernel/fs/nls/nls_base.ko

kernel/fs/nls/nls_cp437.ko

kernel/fs/nls/nls_ascii.ko

kernel/crypto/crypto.ko

kernel/crypto/crypto_wq.ko

kernel/crypto/crypto_algapi.ko

kernel/crypto/aead.ko

kernel/crypto/crypto_blkcipher.ko

kernel/crypto/crypto_hash.ko

kernel/crypto/akcipher.ko

kernel/crypto/kpp.ko

kernel/crypto/crypto_acompress.ko

kernel/crypto/cryptomgr.ko

kernel/crypto/crypto_null.ko

kernel/crypto/cbc.ko

kernel/crypto/des_generic.ko

kernel/crypto/aes_generic.ko

kernel/crypto/crc32c_generic.ko

kernel/crypto/crc32_generic.ko

kernel/crypto/rng.ko

kernel/block/deadline-iosched.ko

kernel/block/cfq-iosched.ko

kernel/block/mq-deadline.ko

kernel/block/kyber-iosched.ko

kernel/drivers/base/firmware_class.ko

kernel/drivers/base/regmap/regmap-i2c.ko

kernel/drivers/base/regmap/regmap-spi.ko

kernel/drivers/block/brd.ko

kernel/drivers/block/loop.ko

kernel/drivers/char/ttyprintk.ko

kernel/drivers/char/raw.ko

kernel/drivers/char/broadcom/vcio.ko

kernel/drivers/char/broadcom/bcm2835-gpiomem.ko

kernel/drivers/char/hw_random/rng-core.ko

kernel/drivers/char/hw_random/bcm2835-rng.ko

kernel/drivers/cpufreq/cpufreq_performance.ko

kernel/drivers/cpufreq/cpufreq_powersave.ko

kernel/drivers/cpufreq/cpufreq_userspace.ko

kernel/drivers/cpufreq/cpufreq_ondemand.ko

kernel/drivers/cpufreq/cpufreq_conservative.ko

kernel/drivers/dma/virt-dma.ko

kernel/drivers/dma/bcm2708-dmaengine.ko

kernel/drivers/dma/bcm2835-dma.ko

kernel/drivers/firmware/raspberrypi.ko

kernel/drivers/hid/hid.ko

kernel/drivers/hid/hid-generic.ko

kernel/drivers/hid/usbhid/usbhid.ko

kernel/drivers/i2c/i2c-core.ko

kernel/drivers/input/input-core.ko

kernel/drivers/input/input-leds.ko

kernel/drivers/input/mousedev.ko

kernel/drivers/input/touchscreen/of_touchscreen.ko

kernel/drivers/leds/led-class.ko

kernel/drivers/leds/leds-gpio.ko

kernel/drivers/leds/trigger/ledtrig-timer.ko

kernel/drivers/leds/trigger/ledtrig-oneshot.ko

kernel/drivers/leds/trigger/ledtrig-heartbeat.ko

kernel/drivers/leds/trigger/ledtrig-backlight.ko

kernel/drivers/leds/trigger/ledtrig-gpio.ko

kernel/drivers/leds/trigger/ledtrig-default-on.ko

kernel/drivers/leds/trigger/ledtrig-input.ko

kernel/drivers/mailbox/bcm2835-mailbox.ko

kernel/drivers/media/rc/rc-core.ko

kernel/drivers/media/rc/ir-nec-decoder.ko

kernel/drivers/media/rc/ir-rc5-decoder.ko

kernel/drivers/media/rc/ir-rc6-decoder.ko

kernel/drivers/media/rc/ir-jvc-decoder.ko

kernel/drivers/media/rc/ir-sony-decoder.ko

kernel/drivers/media/rc/ir-sanyo-decoder.ko

kernel/drivers/media/rc/ir-sharp-decoder.ko

kernel/drivers/media/rc/ir-mce_kbd-decoder.ko

kernel/drivers/media/rc/ir-xmp-decoder.ko

kernel/drivers/media/rc/keymaps/rc-adstech-dvb-t-pci.ko

kernel/drivers/media/rc/keymaps/rc-alink-dtu-m.ko

kernel/drivers/media/rc/keymaps/rc-anysee.ko

kernel/drivers/media/rc/keymaps/rc-apac-viewcomp.ko

kernel/drivers/media/rc/keymaps/rc-asus-pc39.ko

kernel/drivers/media/rc/keymaps/rc-asus-ps3-100.ko

kernel/drivers/media/rc/keymaps/rc-ati-tv-wonder-hd-600.ko

kernel/drivers/media/rc/keymaps/rc-ati-x10.ko

kernel/drivers/media/rc/keymaps/rc-avermedia-a16d.ko

kernel/drivers/media/rc/keymaps/rc-avermedia.ko

kernel/drivers/media/rc/keymaps/rc-avermedia-cardbus.ko

kernel/drivers/media/rc/keymaps/rc-avermedia-dvbt.ko

kernel/drivers/media/rc/keymaps/rc-avermedia-m135a.ko

kernel/drivers/media/rc/keymaps/rc-avermedia-m733a-rm-k6.ko

kernel/drivers/media/rc/keymaps/rc-avermedia-rm-ks.ko

kernel/drivers/media/rc/keymaps/rc-avertv-303.ko

kernel/drivers/media/rc/keymaps/rc-azurewave-ad-tu700.ko

kernel/drivers/media/rc/keymaps/rc-behold.ko

kernel/drivers/media/rc/keymaps/rc-behold-columbus.ko

kernel/drivers/media/rc/keymaps/rc-budget-ci-old.ko

kernel/drivers/media/rc/keymaps/rc-cec.ko

kernel/drivers/media/rc/keymaps/rc-cinergy-1400.ko

kernel/drivers/media/rc/keymaps/rc-cinergy.ko

kernel/drivers/media/rc/keymaps/rc-d680-dmb.ko

kernel/drivers/media/rc/keymaps/rc-delock-61959.ko

kernel/drivers/media/rc/keymaps/rc-dib0700-nec.ko

kernel/drivers/media/rc/keymaps/rc-dib0700-rc5.ko

kernel/drivers/media/rc/keymaps/rc-digitalnow-tinytwin.ko

kernel/drivers/media/rc/keymaps/rc-digittrade.ko

kernel/drivers/media/rc/keymaps/rc-dm1105-nec.ko

kernel/drivers/media/rc/keymaps/rc-dntv-live-dvb-t.ko

kernel/drivers/media/rc/keymaps/rc-dntv-live-dvbt-pro.ko

kernel/drivers/media/rc/keymaps/rc-dtt200u.ko

kernel/drivers/media/rc/keymaps/rc-dvbsky.ko

kernel/drivers/media/rc/keymaps/rc-dvico-mce.ko

kernel/drivers/media/rc/keymaps/rc-dvico-portable.ko

kernel/drivers/media/rc/keymaps/rc-em-terratec.ko

kernel/drivers/media/rc/keymaps/rc-encore-enltv2.ko

kernel/drivers/media/rc/keymaps/rc-encore-enltv.ko

kernel/drivers/media/rc/keymaps/rc-encore-enltv-fm53.ko

kernel/drivers/media/rc/keymaps/rc-evga-indtube.ko

kernel/drivers/media/rc/keymaps/rc-eztv.ko

kernel/drivers/media/rc/keymaps/rc-flydvb.ko

kernel/drivers/media/rc/keymaps/rc-flyvideo.ko

kernel/drivers/media/rc/keymaps/rc-fusionhdtv-mce.ko

kernel/drivers/media/rc/keymaps/rc-gadmei-rm008z.ko

kernel/drivers/media/rc/keymaps/rc-geekbox.ko

kernel/drivers/media/rc/keymaps/rc-genius-tvgo-a11mce.ko

kernel/drivers/media/rc/keymaps/rc-gotview7135.ko

kernel/drivers/media/rc/keymaps/rc-imon-mce.ko

kernel/drivers/media/rc/keymaps/rc-imon-pad.ko

kernel/drivers/media/rc/keymaps/rc-iodata-bctv7e.ko

kernel/drivers/media/rc/keymaps/rc-it913x-v1.ko

kernel/drivers/media/rc/keymaps/rc-it913x-v2.ko

kernel/drivers/media/rc/keymaps/rc-kaiomy.ko

kernel/drivers/media/rc/keymaps/rc-kworld-315u.ko

kernel/drivers/media/rc/keymaps/rc-kworld-pc150u.ko

kernel/drivers/media/rc/keymaps/rc-kworld-plus-tv-analog.ko

kernel/drivers/media/rc/keymaps/rc-leadtek-y04g0051.ko

kernel/drivers/media/rc/keymaps/rc-lme2510.ko

kernel/drivers/media/rc/keymaps/rc-manli.ko

kernel/drivers/media/rc/keymaps/rc-medion-x10.ko

kernel/drivers/media/rc/keymaps/rc-medion-x10-digitainer.ko

kernel/drivers/media/rc/keymaps/rc-medion-x10-or2x.ko

kernel/drivers/media/rc/keymaps/rc-msi-digivox-ii.ko

kernel/drivers/media/rc/keymaps/rc-msi-digivox-iii.ko

kernel/drivers/media/rc/keymaps/rc-msi-tvanywhere.ko

kernel/drivers/media/rc/keymaps/rc-msi-tvanywhere-plus.ko

kernel/drivers/media/rc/keymaps/rc-nebula.ko

kernel/drivers/media/rc/keymaps/rc-nec-terratec-cinergy-xs.ko

kernel/drivers/media/rc/keymaps/rc-norwood.ko

kernel/drivers/media/rc/keymaps/rc-npgtech.ko

kernel/drivers/media/rc/keymaps/rc-pctv-sedna.ko

kernel/drivers/media/rc/keymaps/rc-pinnacle-color.ko

kernel/drivers/media/rc/keymaps/rc-pinnacle-grey.ko

kernel/drivers/media/rc/keymaps/rc-pinnacle-pctv-hd.ko

kernel/drivers/media/rc/keymaps/rc-pixelview.ko

kernel/drivers/media/rc/keymaps/rc-pixelview-mk12.ko

kernel/drivers/media/rc/keymaps/rc-pixelview-002t.ko

kernel/drivers/media/rc/keymaps/rc-pixelview-new.ko

kernel/drivers/media/rc/keymaps/rc-powercolor-real-angel.ko

kernel/drivers/media/rc/keymaps/rc-proteus-2309.ko

kernel/drivers/media/rc/keymaps/rc-purpletv.ko

kernel/drivers/media/rc/keymaps/rc-pv951.ko

kernel/drivers/media/rc/keymaps/rc-hauppauge.ko

kernel/drivers/media/rc/keymaps/rc-rc6-mce.ko

kernel/drivers/media/rc/keymaps/rc-real-audio-220-32-keys.ko

kernel/drivers/media/rc/keymaps/rc-reddo.ko

kernel/drivers/media/rc/keymaps/rc-snapstream-firefly.ko

kernel/drivers/media/rc/keymaps/rc-streamzap.ko

kernel/drivers/media/rc/keymaps/rc-tbs-nec.ko

kernel/drivers/media/rc/keymaps/rc-technisat-ts35.ko

kernel/drivers/media/rc/keymaps/rc-technisat-usb2.ko

kernel/drivers/media/rc/keymaps/rc-terratec-cinergy-c-pci.ko

kernel/drivers/media/rc/keymaps/rc-terratec-cinergy-s2-hd.ko

kernel/drivers/media/rc/keymaps/rc-terratec-cinergy-xs.ko

kernel/drivers/media/rc/keymaps/rc-terratec-slim.ko

kernel/drivers/media/rc/keymaps/rc-terratec-slim-2.ko

kernel/drivers/media/rc/keymaps/rc-tevii-nec.ko

kernel/drivers/media/rc/keymaps/rc-tivo.ko

kernel/drivers/media/rc/keymaps/rc-total-media-in-hand.ko

kernel/drivers/media/rc/keymaps/rc-total-media-in-hand-02.ko

kernel/drivers/media/rc/keymaps/rc-trekstor.ko

kernel/drivers/media/rc/keymaps/rc-tt-1500.ko

kernel/drivers/media/rc/keymaps/rc-twinhan-dtv-cab-ci.ko

kernel/drivers/media/rc/keymaps/rc-twinhan1027.ko

kernel/drivers/media/rc/keymaps/rc-videomate-m1f.ko

kernel/drivers/media/rc/keymaps/rc-videomate-s350.ko

kernel/drivers/media/rc/keymaps/rc-videomate-tv-pvr.ko

kernel/drivers/media/rc/keymaps/rc-winfast.ko

kernel/drivers/media/rc/keymaps/rc-winfast-usbii-deluxe.ko

kernel/drivers/media/rc/keymaps/rc-su3000.ko

kernel/drivers/media/rc/keymaps/rc-zx-irdec.ko

kernel/drivers/mfd/mfd-core.ko

kernel/drivers/mmc/core/mmc_core.ko

kernel/drivers/mmc/core/pwrseq_simple.ko

kernel/drivers/mmc/core/pwrseq_emmc.ko

kernel/drivers/mmc/core/mmc_block.ko

kernel/drivers/mmc/host/sdhci.ko

kernel/drivers/mmc/host/bcm2835-mmc.ko

kernel/drivers/mmc/host/bcm2835-sdhost.ko

kernel/drivers/mmc/host/sdhci-pltfm.ko

kernel/drivers/net/mii.ko

kernel/drivers/net/usb/smsc95xx.ko

kernel/drivers/net/usb/usbnet.ko

kernel/drivers/nvmem/nvmem_core.ko

kernel/drivers/scsi/scsi_mod.ko

kernel/drivers/scsi/scsi_transport_iscsi.ko

kernel/drivers/scsi/sd_mod.ko

kernel/drivers/staging/vc04_services/vchiq.ko

kernel/drivers/thermal/thermal_sys.ko

kernel/drivers/thermal/broadcom/bcm2835_thermal.ko

kernel/drivers/tty/serial/serial_core.ko

kernel/drivers/tty/serial/amba-pl011.ko

kernel/drivers/tty/serial/kgdboc.ko

kernel/drivers/tty/serial/8250/8250.ko

kernel/drivers/tty/serial/8250/8250_base.ko

kernel/drivers/tty/serial/8250/8250_bcm2835aux.ko

kernel/drivers/tty/serial/8250/8250_of.ko

kernel/drivers/usb/common/usb-common.ko

kernel/drivers/usb/core/usbcore.ko

kernel/drivers/usb/storage/usb-storage.ko

kernel/drivers/video/backlight/backlight.ko

kernel/drivers/video/fbdev/bcm2708_fb.ko

kernel/drivers/video/fbdev/core/fb.ko

kernel/drivers/video/fbdev/core/cfbfillrect.ko

kernel/drivers/video/fbdev/core/cfbcopyarea.ko

kernel/drivers/video/fbdev/core/cfbimgblt.ko

kernel/drivers/watchdog/bcm2835_wdt.ko

kernel/sound/soundcore.ko

kernel/net/dns_resolver/dns_resolver.ko

kernel/net/ipv4/tcp_cubic.ko

kernel/net/packet/af_packet.ko

kernel/net/sunrpc/sunrpc.ko

kernel/net/sunrpc/auth_gss/auth_rpcgss.ko

kernel/net/unix/unix.ko

kernel/net/xfrm/xfrm_algo.ko

kernel/net/xfrm/xfrm_user.ko

kernel/lib/bitrev.ko

kernel/lib/crc16.ko

kernel/lib/crc-itu-t.ko

kernel/lib/crc32.ko

kernel/lib/libcrc32c.ko

kernel/lib/oid_registry.ko

kernel/lib/fonts/font.ko

kernel/lib/lz4/lz4_decompress.ko

kernel/lib/lzo/lzo_decompress.ko

kernel/lib/xz/xz_dec.ko

kernel/lib/zlib_inflate/zlib_inflate.ko

**Comment by yu55** [comment]
Hi @louisluyckx1telenetbe 
Your system is probably missing some kernel development packages, maybe raspberrypi-kernel-headers or something similar. Try to google why your system is missing this directory.
Please also check this link: https://raspberrypi.stackexchange.com/questions/50240/missing-build-file-when-building-for-rtl8812au-driver

**Comment by ghost** [comment]
Many thanks for your help.

⁣Mvg

Louis Luyckx​

Op 13 jan. 2019 22:52, om 22:52, Marcin P <notifications@github.com> schreef:

**Comment by yu55** [comment]
@louisluyckx1telenetbe No problem. Glad I could help. If you like this project don't forget to add a star ;)
Cheers.
