### ISSUE TITLE
multiple 1w sensors on same pin

### ISSUE THREAD

**Issue by transistorgit** [yu55/multi-am2301#2]
Hi!

very interesting project.
One question that was not obvious from your readme:
Are there multiple devices allowed on one 1W bus, or must each have it's own pin?
Example: I have 5 DS1820 on one bus line and want to add a DHT21 on the same wire.

Brds
Bernd

**Comment by yu55** [comment]
Hi @transistorgit 
Thank you for your comment. Very good question.
Each DHT sensor must have its own pin. "One-wire" in DHT sensors is totally different than 1-Wire made by Dallas Semiconductor (used by DS1820). Dallas 1-Wire requires connected devices to have a unique 64-bit address (written in their internal ROM), so you can select which device you want to commnicate, using just single common wire. DHT sensor doesn't have any kind of address, so each DHT sensor requires it's own signal pin in microcontroller. So i guess DHT "One-wire" is not really a bus anyway. Search google for "dht21 datasheet" and you will easily find documents describing how DHT works (it's quite easy and straightforward).
Greetings :)

P.S.
If you like my project please give it a star (maybe more people will find it, use it and make it better). Thanks :)

**Comment by transistorgit** [comment]
Ok, then it‘s clear. I just thought, 1wire is the same, as I think Dallas 1wire is quite famous. Then I will have to use another pin.
brgs
Bernd
